os: linux
dist: xenial
language: python
addons:
  apt:
    packages:
      - libgnutls-dev
  
  
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
  
script: python3 -m cfunc/test_sample.py
# script: pytest # run tests
after_success:
  - codecov # submit coverage
